### ISSUE TITLE
wont compile "analogSerial example

### ISSUE THREAD

**Issue by sguwi** [adafruit/Adafruit-Feather-M0-Adalogger-PCB#1]
Try to load simple "AnalogReadSerial example but keep getting:

 java.io.IOException: Cannot run program "{runtime.tools.bossac-1.7.0.path}/bossac.exe": CreateProcess error=2, Can't find the file.

I have installed JRE and JDK and JAVA_HOME   

 /*AnalogReadSerial

  Reads an analog input on pin 0, prints the result to the Serial Monitor.
  Graphical representation is available using Serial Plotter (Tools > Serial Plotter menu).
  Attach the center pin of a potentiometer to pin A0, and the outside pins to +5V and ground.

  This example code is in the public domain.

  http://www.arduino.cc/en/Tutorial/AnalogReadSerial
*/

// the setup routine runs once when you press reset:
void setup() {
  // initialize serial communication at 9600 bits per second:
  Serial.begin(9600);
}

// the loop routine runs over and over again forever:
void loop() {
  // read the input on analog pin 0:
  int sensorValue = analogRead(A0);
  // print out the value you read:
  Serial.println(sensorValue);
  delay(1);        // delay in between reads for stability
}

**Comment by ladyada** [comment]
hiya - this is the github for the PCB
tech support for adafruit products is handled in the forums, thx :)
