### ISSUE TITLE
Grounding of filtering caps on VDDCORE and +3V3

### ISSUE THREAD

**Issue by nysfred** [adafruit/Adafruit-Feather-M0-Adalogger-PCB#3]
When I looked at PCB layout, I don't see caps C1 and C7 connected to GND.
Moreover, in schematics I don't see VDDCore connected to anything but the cap.

Is it a mistake or something I don't understand?

**Comment by ladyada** [comment]
there's a ground plane that you have to fill to see GND. it is correct

**Comment by nysfred** [comment]
Sorry for my ignorance, first time I am using Eagle. Have you done it in the file and it is just a question of displaying it or it shall be done just before manufacturing?

Thanks anyway for your work!
