### ISSUE TITLE
Hardware revision request: microSD power control

### ISSUE THREAD

**Issue by adamgarbo** [adafruit/Adafruit-Feather-M0-Adalogger-PCB#4]
Hi @ladyada,

The Adafruit Feather M0 Adalogger represents a valuable tool for data collection in the natural sciences. However, its biggest drawback is that power to the microSD card can not be disabled. As you know, the current draw of microSD cards can be significant, even when idle, and low-power operation is critical for many scientific applications. 

This feature has been requested many times on the Adafruit forums. Would you consider adding power control circuitry to allow the Adalogger to disable power to the microSD?

Cheers,
Adam

**Comment by ladyada** [comment]
this board isnt likely to be revised, however maybe some other board will!
