### ISSUE TITLE
Possible to get the BOM?

### ISSUE THREAD

**Issue by rrainey** [adafruit/Adafruit-Feather-M0-Adalogger-PCB#5]
I was trying to locate the manufacturer's part number of the crystal used to drive the SAMD21 in this project.  Would it be possible to add the full BOM to the source?

Thanks.

**Comment by ladyada** [comment]
any non-specific-part-numbers are generic components that we may sub as needed
https://www.digikey.com/en/products/detail/fox-electronics/FK135EIHM0-032768-T3/1024594  will probably work
